version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: skymarket
      POSTGRES_PASSWORD: skymarket
      POSTGRES_DB: skymarket
    restart: always
    ports:
      - "5432:5432"
    networks:
      - db_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U skymarket -d skymarket" ]
      interval: 5s
      timeout: 5s
      retries: 5


  migrations:
    build: skymarket/skymarket
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loadall"
    networks:
      - db_network


  api:
    build: skymarket/skymarket
    image: skymarket:latest
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - nginx_network
      - db_network


  frontend:
    build: frontend_react
    volumes:
      - frontend:/app/build
    depends_on:
      - db
      - api
    networks:
      - nginx_network


  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./skymarket/django_static/:/usr/share/nginx/html/django_static/
      - ./skymarket/django_media/:/usr/share/nginx/html/django_media/
      - ./market_postgres/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      db:
        condition: service_healthy
      frontend:
        condition: service_completed_successfully
      api:
        condition: service_started
    networks:
      - nginx_network


volumes:
  postgres_data:
  frontend:


networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge